let JOBS = [
  {
    company: "Bovisync",
    title: "Web Developer & Project Manager",
    description: "",
    start_date: "July 2021",
    end_date: "current",
    activities: [
      "Assumed role as Engineering Manager after CTO departure, led sprints, personnel management, hiring, and product planning",
      "Worked daily with Product and Engineering teams to ensure company vision was being executed as manageable, technical tasks",
      "Wireframed, built, and launched progressive web app for optimizing cow diets using Ionic Vue, GraphQL, and Django",
      "Completed multi-year company objective to modernizing data visualization service for large data sets by implementing and customizing Plotly.js",
      "Updated and simplified drug-inventory tracking system user interface to be compatible with European farming standards",
      "Upgraded entire monolith codebase for ES6 compatibility and migrated to Rollup to decrease bundling times",
    ],
  },
  {
    company: "Actualize Coding Bootcamp",
    title: "Web Development Teaching Assistant",
    description: "",
    start_date: "May 2021",
    end_date: "July 2021",
    activities: [
      "Taught students how to ideate, architect, iterate, and build RESTful CRUD web applications",
      "Focused on teaching proficiency in Ruby, Rails, Javascript, VueJS, and PostgreSQL",
      "Held private office hours to help students learn new topics or round-out understanding of concepts covered in class",
    ],
  },
  {
    company: "Actualize Coding Bootcamp",
    title: "Web Development Student",
    description: "",
    start_date: "December 2020",
    end_date: "May 2021",
    activities: [
      "Learned fundamentals and best practices in full-stack web development in areas of project architecture, backend, frontend, and how to effectively self-teach new technologies",
      "Generated technical requirements and determined the most effective solutions, created wireframes, designed schema, and researched outside resources",
      "Built and tested the backend, incorporating external APIs",
      "Created pages and RESTful routes, made web requests to retrieve data, formatted and styled results, incorporated libraries and themes",
    ],
  },
  {
    company: "Joe Chocolate Company",
    title: "Co-Founder & CEO",
    description:
      "Naturally caffeinated dark chocolate. Locally produced, nationally distributed, internationally enjoyed.",
    start_date: "March 2016",
    end_date: "December 2020",
    activities: [
      "Started business as an undergraduate class project and a two-man operation out of the back of a fish-n-chips restaurant",
      "Developed product, recipes, and manufacturing practices",
      "Built and implemented software for websites, CRM, fulfillment, and forecasting",
      "Closed multiple rounds of funding with angel investors and private equity",
      "Expanded wholesale business 300+ locations including REI, Whole Foods, and Nordstorm",
      "Managed wholesale and retail operations, employing over 20 staff members",
      "Managed construction and opened retail facility in Pike Place Market, serving 50K+ customers per year",
    ],
  },
  {
    company: "Caveman Dirtbag Sponsorship",
    title: "Founder",
    description: "Fueling thru-hikers on the Pacific Crest Trail",
    start_date: "March 2016",
    end_date: "December 2020",
    activities: [
      "Created business co-op to sponsor thru-hikers on the PCT",
      "Partnered with Patagonia Seattle, Arc'teryx, Enlightened Equipment, and other outdoor brands",
      "Selected 2-4 hikers each year to receive cash, gear, and food in care-packages",
      "Recognized as preeminent sponsorship amongst thru-hikers and received hundreds of applications each year",
      "Sponsored hikers from countries including Brazil, New Zealand, and Israel",
    ],
  },
  {
    company: "Peach",
    title: "Business Development Associate",
    description: "",
    start_date: "August 2016",
    end_date: "November 2016",
    activities: [
      "Performed sales cycle from discovery, to cold calling, to activation of lunch delivery program",
      "Onboarded 30+ businesses onto Peach lunch delivery platform including two of Seattle's largest hospitals, JP Morgan, and Weyerhaeuser's headquarters",
      "Developed best practices for activating healthcare providers",
    ],
  },
  {
    company: "CardSwapper",
    title: "Co-Founder & CEO",
    description: "The world's first peer-to-peer trading and liquidation platform for unused and unwanted gift cards",
    start_date: "February 2013",
    end_date: "June 2016",
    activities: [
      "Co-founded business as an undergraduate freshman at the University of Washington",
      "Designed and wire-framed application ",
      "Hired and managed team to develop, and launch application on iOS app store",
      "Raised seed funding from Jones + Foster Accelerator and from private investors",
      "Wrote, submitted, and received patent from the United States Patent and Trademark Office for novel methods of digital gift card exchange ",
      "Partnered with nations largest gift card liquidation platform to launch cash-for-cards feature",
    ],
  },
  {
    company: "UW School of Music",
    title: "Student Visual & Audio Archiver",
    description: "",
    start_date: "October 2013",
    end_date: "May 2016",
    activities: [
      "Recorded, live-mixed, and produced live classical, jazz, choral, and orchestral performances in high-fidelity",
      "Self-taught Logic Pro, Audacity, and Premiere Pro to increase quality of archived media ",
      "Hired independently by graduate students to produce thesis performances due to quality of work",
    ],
  },
  {
    company: "Tango Card",
    title: "Social Networking Intern",
    description: "",
    start_date: "October 2013",
    end_date: "May 2016",
    activities: [
      "Managed Facebook, Twitter, and Linkedin social profiles via Hootsuite",
      "Deployed social marketing strategies focused on increasing relevance amongst key demographics",
      "Nearly doubled Twitter following using unpaid-marketing strategies",
    ],
  },
];

const PROFILE = {
  name: "Samuel Tanner",
  phone: "360.878.0730",
  email: "samuel.m.s.tanner@gmail.com",
  title: "Web Developer",
  blurb: "Entrepreneur and developer. I love turning neat ideas into beautiful realities.",
};

const LINKS = {
  mail: "mail",
  linkedIn: "https://www.linkedin.com/in/samueltanner/",
  github: "https://github.com/samueltanner",
};
const SKILLS = [
  { name: "Adobe Illustrator", score: 5 },
  { name: "Adobe Lightroom", score: 5 },
  { name: "Adobe Photoshop", score: 5 },
  { name: "Adobe Premiere", score: 3 },
  { name: "Adobe XD", score: 5 },
  { name: "Airtable", score: 5, dev_skill: true },
  { name: "AngularJS", score: 2, dev_skill: true },
  { name: "Creating & Maintaining API's", score: 4, dev_skill: true },
  { name: "Bootstrap", score: 4, dev_skill: true },
  { name: "Cold Calling", score: 5 },
  { name: "CRUD Applications", score: 3, dev_skill: true },
  { name: "Customer Relationship Management", score: 5 },
  { name: "Django", score: 3, dev_skill: true },
  { name: "Financial Projections", score: 3 },
  { name: "Fundraising", score: 5 },
  { name: "Git/GitHub/version control", score: 3, dev_skill: true },
  { name: "GraphQL", score: 3, dev_skill: true },
  { name: "HTML", score: 4, dev_skill: true },
  { name: "Ionic Framework", score: 4, dev_skill: true },
  { name: "Javascript", score: 5, dev_skill: true },
  { name: "Logic Pro", score: 5 },
  { name: "Marketing Strategy & Rollout", score: 5 },
  { name: "Microsoft Excel", score: 5 },
  { name: "Notion", score: 5, dev_skill: true },
  { name: "Object Oriented Programming", score: 3, dev_skill: true },
  { name: "Pair Programming", score: 5, dev_skill: true },
  { name: "Plotly.js", score: 3, dev_skill: true },
  { name: "PostgreSQL", score: 3, dev_skill: true },
  { name: "Project Management", score: 4, dev_skill: true },
  { name: "Python", score: 3, dev_skill: true },
  { name: "React.js", score: 4, dev_skill: true },
  { name: "REST APIs", score: 4, dev_skill: true },
  { name: "Rollup.js", score: 5 },
  { name: "Ruby on Rails", score: 4, dev_skill: true },
  { name: "Ruby", score: 4, dev_skill: true },
  { name: "Sales & Sales Management", score: 5 },
  { name: "Tailwind CSS", score: 5, dev_skill: true },
  { name: "Team Management", score: 5 },
  { name: "Video Editing", score: 4 },
  { name: "Vue.js", score: 4, dev_skill: true },
  { name: "Web Development", score: 4, dev_skill: true },
  { name: "Wholesale Management", score: 5 },
  { name: "Wire-framing", score: 5, dev_skill: true },
];

export const jobs = JOBS;
export const profile = PROFILE;
export const links = LINKS;
export const skills = SKILLS;
